#!/usr/bin/env python3
"""
Extract bundled Sudoku puzzles from the Kotlin source and emit an equivalent
Swift file. Used during the iOS greenfield rebuild to preserve the
1,200-puzzle dataset without retyping.

The Kotlin source uses:
    val EASY: List<String> = listOf(
        "0507030600070008000008160000...",  // 81-char puzzle string
        ...
    )

Optionally puzzles may carry ratings as "..." to 1.3f (Kotlin Pair syntax).
This script handles both forms.

Mirrors the existing iosApp/iosApp/Engine/BundledPuzzles.swift format
([String] per difficulty) when no ratings are present in the source.

Usage:
    python extract_swift_puzzles.py [--source PATH] [--output PATH] [--validate]
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

DIFFICULTIES = ["EASY", "MEDIUM", "HARD", "EXPERT"]
PUZZLE_REGEX = re.compile(r"^[0-9]{81}$")
EXPECTED_PER_DIFFICULTY = 300


def find_kotlin_source(default: Path | None) -> Path:
    """Locate the Kotlin BundledPuzzles.kt file."""
    if default and default.is_file():
        return default
    # Walk up from this script and search under shared/src.
    root = Path(__file__).resolve().parent.parent
    candidates = list(root.glob("shared/src/**/BundledPuzzles.kt"))
    if not candidates:
        candidates = list(root.glob("**/BundledPuzzles.kt"))
    if not candidates:
        print("ERROR: Could not find BundledPuzzles.kt anywhere under shared/src/.",
              file=sys.stderr)
        sys.exit(1)
    return candidates[0]


def find_existing_swift(root: Path) -> Path | None:
    """Locate an existing BundledPuzzles.swift to mirror its format."""
    for c in root.glob("iosApp/**/BundledPuzzles.swift"):
        return c
    for c in root.glob("**/BundledPuzzles.swift"):
        # Avoid matching our own output in scripts/.
        if "scripts" not in c.parts:
            return c
    return None


def parse_kotlin(path: Path) -> dict[str, list[tuple[str, float | None]]]:
    """Parse Kotlin source into {difficulty: [(puzzle, rating_or_None), ...]}.

    Supports both bare strings ("0123...") and Kotlin Pair syntax
    ("0123..." to 1.3f).
    """
    text = path.read_text(encoding="utf-8")
    result: dict[str, list[tuple[str, float | None]]] = {}

    # Regex for "val EASY: List<...> = listOf(\n  ...content...\n)"
    block_re = re.compile(
        r"val\s+(EASY|MEDIUM|HARD|EXPERT)\s*:\s*List<[^>]+>\s*=\s*listOf\s*\("
        r"(.*?)"
        r"\)\s*(?:\n|$)",
        re.DOTALL,
    )

    # Two entry forms:
    #   bare:    "0123..."
    #   paired:  "0123..." to 1.3f
    entry_re = re.compile(
        r'"([0-9]{81})"\s*(?:to\s*(-?\d+(?:\.\d+)?)f?)?',
    )

    for m in block_re.finditer(text):
        diff = m.group(1)
        body = m.group(2)
        entries: list[tuple[str, float | None]] = []
        for em in entry_re.finditer(body):
            puzzle = em.group(1)
            rating_str = em.group(2)
            rating = float(rating_str) if rating_str is not None else None
            if not PUZZLE_REGEX.match(puzzle):
                # Locate approximate line number for error reporting.
                line_no = text.count("\n", 0, m.start() + em.start(1)) + 1
                print(f"ERROR: Invalid puzzle string at line {line_no}: {puzzle!r}",
                      file=sys.stderr)
                sys.exit(2)
            entries.append((puzzle, rating))
        result[diff] = entries

    for d in DIFFICULTIES:
        if d not in result:
            print(f"ERROR: Difficulty '{d}' not found in Kotlin source.", file=sys.stderr)
            sys.exit(3)

    return result


def emit_swift(
    data: dict[str, list[tuple[str, float | None]]],
    source_rel: str,
    has_ratings: bool,
    source_mtime: float,
) -> str:
    """Generate Swift file contents.

    The "Last regenerated" timestamp is derived from the source file's mtime,
    not wall-clock time, so re-running on an unchanged source produces
    byte-identical output (script is idempotent).
    """
    timestamp = datetime.fromtimestamp(source_mtime, tz=timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )
    total = sum(len(v) for v in data.values())
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by scripts/extract_swift_puzzles.py - do not edit by hand.")
    lines.append(f"// Source: {source_rel}")
    lines.append("// Regenerate: python scripts/extract_swift_puzzles.py")
    lines.append(f"// Last regenerated: {timestamp}")
    lines.append(f"// Total puzzles: {total} (300 per difficulty x 4 difficulties)")
    lines.append("")
    lines.append("import Foundation")
    lines.append("")
    lines.append("enum BundledPuzzles {")

    swift_names = {"EASY": "easy", "MEDIUM": "medium", "HARD": "hard", "EXPERT": "expert"}

    for diff in DIFFICULTIES:
        entries = data[diff]
        name = swift_names[diff]
        if has_ratings:
            lines.append(f"    static let {name}: [(puzzle: String, rating: Double)] = [")
            for puzzle, rating in entries:
                r = rating if rating is not None else 0.0
                lines.append(f'        ("{puzzle}", {r}),')
            lines.append("    ]")
        else:
            lines.append(f"    static let {name}: [String] = [")
            for puzzle, _ in entries:
                lines.append(f'        "{puzzle}",')
            lines.append("    ]")
        lines.append("")

    if has_ratings:
        lines.append("    static let all: [String: [(puzzle: String, rating: Double)]] = [")
        lines.append('        "easy": easy, "medium": medium, "hard": hard, "expert": expert')
        lines.append("    ]")
    else:
        lines.append("    static let all: [String: [String]] = [")
        lines.append('        "easy": easy, "medium": medium, "hard": hard, "expert": expert')
        lines.append("    ]")
        lines.append("")
        lines.append("    static func bank(for difficulty: Difficulty) -> [String] {")
        lines.append("        switch difficulty {")
        lines.append("        case .easy:   return easy")
        lines.append("        case .medium: return medium")
        lines.append("        case .hard:   return hard")
        lines.append("        case .expert: return expert")
        lines.append("        }")
        lines.append("    }")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def validate(
    data: dict[str, list[tuple[str, float | None]]],
) -> list[str]:
    """Validate puzzle data; returns list of warning strings (errors exit)."""
    warnings: list[str] = []
    for diff in DIFFICULTIES:
        entries = data[diff]
        if len(entries) != EXPECTED_PER_DIFFICULTY:
            warnings.append(
                f"WARN: {diff} has {len(entries)} puzzles, expected {EXPECTED_PER_DIFFICULTY}."
            )
        seen: set[str] = set()
        for puzzle, _ in entries:
            if not PUZZLE_REGEX.match(puzzle):
                print(f"ERROR: {diff} contains invalid puzzle string: {puzzle!r}",
                      file=sys.stderr)
                sys.exit(4)
            if puzzle in seen:
                warnings.append(f"WARN: {diff} contains duplicate puzzle: {puzzle[:20]}...")
            seen.add(puzzle)
    return warnings


def validate_swift_output(path: Path) -> list[str]:
    """Re-parse the emitted Swift file and validate counts / format."""
    text = path.read_text(encoding="utf-8")
    warnings: list[str] = []
    # Match either tuple form: ("...", N) or bare form: "...",
    # Group by enclosing static let block.
    block_re = re.compile(
        r"static\s+let\s+(easy|medium|hard|expert)\s*:\s*"
        r"\[[^\]]+\]\s*=\s*\[(.*?)\]",
        re.DOTALL,
    )
    tuple_re = re.compile(r'\("([0-9]{81})"\s*,\s*(-?\d+(?:\.\d+)?)\)')
    bare_re = re.compile(r'"([0-9]{81})"')

    found: dict[str, list[str]] = {}
    for m in block_re.finditer(text):
        name = m.group(1)
        body = m.group(2)
        puzzles = [p for p in tuple_re.findall(body)] or [
            (p, None) for p in bare_re.findall(body)
        ]
        # Normalise: collect just puzzle strings.
        if puzzles and isinstance(puzzles[0], tuple) and len(puzzles[0]) == 2:
            strs = [t[0] for t in puzzles]
        else:
            strs = puzzles  # type: ignore[assignment]
        found[name] = strs

    expected_keys = {"easy", "medium", "hard", "expert"}
    if set(found.keys()) != expected_keys:
        warnings.append(
            f"WARN: Swift output missing difficulties; got {sorted(found.keys())}"
        )

    for key, strs in found.items():
        if len(strs) != EXPECTED_PER_DIFFICULTY:
            warnings.append(
                f"WARN: Swift {key} has {len(strs)} puzzles, expected {EXPECTED_PER_DIFFICULTY}."
            )
        for s in strs:
            if not PUZZLE_REGEX.match(s):
                print(f"ERROR: Swift output contains invalid puzzle: {s!r}",
                      file=sys.stderr)
                sys.exit(5)
        if len(set(strs)) != len(strs):
            warnings.append(f"WARN: Swift {key} contains duplicate puzzles.")
    return warnings


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=None,
                        help="Path to Kotlin BundledPuzzles.kt (auto-detected if omitted).")
    parser.add_argument("--output", type=Path,
                        default=Path(__file__).resolve().parent / "BundledPuzzles.swift",
                        help="Path to write Swift output.")
    parser.add_argument("--validate", action="store_true",
                        help="Re-parse the emitted Swift file and confirm round-trip.")
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parent.parent
    kotlin_path = find_kotlin_source(args.source)
    print(f"Source: {kotlin_path}")

    data = parse_kotlin(kotlin_path)
    has_ratings = any(
        any(r is not None for _, r in entries) for entries in data.values()
    )

    warnings = validate(data)
    for w in warnings:
        print(w)

    try:
        source_rel = kotlin_path.relative_to(project_root).as_posix()
    except ValueError:
        source_rel = kotlin_path.as_posix()

    source_mtime = kotlin_path.stat().st_mtime
    swift_text = emit_swift(data, source_rel, has_ratings, source_mtime)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(swift_text, encoding="utf-8", newline="\n")

    counts = ", ".join(f"{d.lower()}={len(data[d])}" for d in DIFFICULTIES)
    size = args.output.stat().st_size
    print(f"Wrote: {args.output} ({size} bytes)")
    print(f"Counts: {counts}")
    print(f"Has ratings: {has_ratings}")

    if args.validate:
        print("\nValidating round-trip...")
        rt_warnings = validate_swift_output(args.output)
        for w in rt_warnings:
            print(w)
        if not rt_warnings:
            print("OK: Swift output round-trips cleanly.")
        warnings.extend(rt_warnings)

    return 0 if not warnings else 0  # warnings are non-fatal


if __name__ == "__main__":
    sys.exit(main())
